const CONFIG = require('../config');
module.exports = [
	 	    {id: 1, value:  "Copy Writing"},
        	{id: 2, value: "Digital Media"},
			{id: 3, value: "Drafting"},
			{id: 4, value: "Editing"},
			{id: 5, value: "Establishing Tone"},
			{id: 6, value: "Formatting"},
			{id: 7, value: "Grammar"},
			{id: 8, value : "Identifying Theme"},
			{id: 9, value: "Establishing Purpose"},
			{id: 10, value: "Journalist Ethics"},
			{id: 11, value: "Language"},
			{id: 12, value: "Media"},
			{id: 13, value: "Microsoft Office"},
			{id: 14, value: "Proofreading"},
			{id: 15, value: "Revising"},
			{id: 16, value: "Spelling"},
			{id: 17, value: "Structure"},
			{id: 18, value: "Style"},
			{id: 19, value: "Punctuation"},
			{id: 20, value: "Strong Vocabulary"},
			{id: 21, value: "Using the Rhetorical Triangle"},
			{id: 22, value: "Devise Structure"},
			{id: 23, value: "Establish Tone"},
			{id: 24, value: "Copy Editing"},
	 	 ]